version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ryankanno"
    commit-message:
      prefix: "build(github)"
    groups:
      gha:
        update-types:
          - "major"
          - "minor"
          - "patch"
    labels:
      - "github-actions"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "ryankanno"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      dev:
        dependency-type: "development"
    open-pull-requests-limit: 10
    labels:
      - "automerge"
      - "pip"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "{{cookiecutter.package_name}}"
    schedule:
      interval: "weekly"
    assignees:
      - "ryankanno"
    commit-message:
      prefix: "build(github)"
    groups:
      gha:
        update-types:
          - "major"
          - "minor"
          - "patch"
    labels:
      - "github-actions"

  - package-ecosystem: "pip"
    directory: "{{cookiecutter.package_name}}"
    schedule:
      interval: "weekly"
    assignees:
      - "ryankanno"
    commit-message:
      prefix: "build"
      include: "scope"
    open-pull-requests-limit: 10
    labels:
      - "automerge"
      - "pip"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "{{cookiecutter.package_name}}"
    schedule:
      interval: "weekly"
    assignees:
      - "ryankanno"
    commit-message:
      prefix: "build(docker)"
    labels:
      - "docker"
      - "dependencies"
