version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/{{cookiecutter.package_name}}"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/{{cookiecutter.package_name}}"
    schedule:
      interval: "daily"
