version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: build(github-actions)
    labels:
      - "github-actions"

  - package-ecosystem: "pip"
    directory: "/{{cookiecutter.package_name}}"
    schedule:
      interval: "daily"
    commit-message:
      prefix: build
      include: scope
    open-pull-requests-limit: 10
    labels:
      - "pip"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/{{cookiecutter.package_name}}"
    schedule:
      interval: "daily"
    commit-message:
      prefix: build(docker)
    labels:
      - "docker"
      - "dependencies"
