ci/cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'pyproject.toml'

docs:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - '**/README.*'

source:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - 'hooks/**/*'
      - all-globs-to-all-files:
        - '!docs/*'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**/*'

python:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.py'
