ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - '.pre-commit-config.yml'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'pyproject.toml'

docs:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - '**/README*'

source:
  - changed-files:
    - any-glob-to-any-file:
      - 'hooks/**/*'
      - '!docs/*'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**/*'
