name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"

categories:
  - title: ":rocket: Features"
    collapse-after: 5
    labels: [feature]
  - title: ":wrench: Fixes & Refactoring"
    collapse-after: 3
    labels: [fix, refactor]
  - title: ":package: Build System & CI/CD"
    collapse-after: 3
    labels: [build]
  - title: ":boom: Breaking Changes"
    labels: [breaking]
  - title: ":pencil: Documentation"
    collapse-after: 3
    labels: [documentation]
  - title: ":arrow_up: Updated Dependencies"
    collapse-after: 1
    labels: [dependencies]
  - title: ":rocket: Performance"
    collapse-after: 3
    labels: [performance]


version-resolver:
  minor:
    labels:
      - 'breaking'
      - 'feature'
  patch:
    labels:
      - 'fix'
      - 'refactor'
      - 'build'
      - 'documentation'
      - 'dependencies'
      - 'performance'
  default: patch

template: |
  ## What’s Changed

  $CHANGES

  ### This release is brought to you by the following wonderful contributors:

  $CONTRIBUTORS

exclude-labels:
  - "skip-changelog"

autolabeler:
  - label: "documentation"
    branch:
      - '/docs{0,1}\/.+/'
  - label: "feature"
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
  - label: "build"
    branch:
      - '/build\/.+/'
  - label: "fix"
    branch:
      - '/fix\/.+/'
  - label: "performance"
    branch:
      - '/perf\/.+/'
  - label: "refactor"
    branch:
      - '/refactor\/.+/'
  - label: "breaking"
    branch:
      - '/breaking\/.+/'
