name: pr-labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened, closed]

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
        sync-labels: true
